### ISSUE TITLE
Customizing doc of class based views

### ISSUE THREAD

**Issue by msmiiit** [m-haziq/django-rest-swagger-docs#7]
is it possible to write custom yaml file in cbv as i need to send more  query params in request.

**Comment by m-haziq** [comment]
Yes you can write YAML to class based views as well. Look at customization code here:
https://github.com/m-haziq/django-rest-swagger-docs/blob/bf10f071dc59b69a2a825c55a0d9b5951e91ad29/demo/swagger_schema.py#L32-L54

In both cases (FBVs and CBVs) it checks if there is YAML then generate params through it otherwise generate with serializer fields.
